using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VideoLibrary.Models;

namespace VideoLibrary.Controllers
{
    public class BookmarkController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ILogger<BookmarkController> _logger;

        public BookmarkController(AppDbContext context, ILogger<BookmarkController> logger)
        {
            _context = context;
            _logger = logger;
        }

        [HttpPost]
        public async Task<IActionResult> Add(int videoId, double timeInSeconds)
        {
            try
            {
                // Verify video exists
                var video = await _context.Videos.FindAsync(videoId);
                if (video == null)
                {
                    return Json(new { success = false, message = "Video not found" });
                }

                // Get current bookmark count for auto-generated name
                var bookmarkCount = await _context.Bookmarks
                    .Where(b => b.VideoId == videoId)
                    .CountAsync();

                var autoGeneratedName = $"Bookmark {bookmarkCount + 1}";

                var bookmark = new Bookmark
                {
                    VideoId = videoId,
                    TimeInSeconds = timeInSeconds,
                    Name = autoGeneratedName,
                    CreatedAt = DateTime.UtcNow,
                    UpdatedAt = DateTime.UtcNow
                };

                _context.Bookmarks.Add(bookmark);
                await _context.SaveChangesAsync();

                return Json(new
                {
                    success = true,
                    bookmark = new
                    {
                        id = bookmark.Id,
                        videoId = bookmark.VideoId,
                        timeInSeconds = bookmark.TimeInSeconds,
                        name = bookmark.Name,
                        formattedTime = FormatTime(bookmark.TimeInSeconds)
                    }
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error adding bookmark for video {VideoId}", videoId);
                return Json(new { success = false, message = "Failed to add bookmark" });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, string name, double timeInSeconds)
        {
            try
            {
                var bookmark = await _context.Bookmarks.FindAsync(id);
                if (bookmark == null)
                {
                    return Json(new { success = false, message = "Bookmark not found" });
                }

                bookmark.Name = name;
                bookmark.TimeInSeconds = timeInSeconds;
                bookmark.UpdatedAt = DateTime.UtcNow;

                await _context.SaveChangesAsync();

                return Json(new
                {
                    success = true,
                    bookmark = new
                    {
                        id = bookmark.Id,
                        videoId = bookmark.VideoId,
                        timeInSeconds = bookmark.TimeInSeconds,
                        name = bookmark.Name,
                        formattedTime = FormatTime(bookmark.TimeInSeconds)
                    }
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating bookmark {BookmarkId}", id);
                return Json(new { success = false, message = "Failed to update bookmark" });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var bookmark = await _context.Bookmarks.FindAsync(id);
                if (bookmark == null)
                {
                    return Json(new { success = false, message = "Bookmark not found" });
                }

                _context.Bookmarks.Remove(bookmark);
                await _context.SaveChangesAsync();

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting bookmark {BookmarkId}", id);
                return Json(new { success = false, message = "Failed to delete bookmark" });
            }
        }

        private string FormatTime(double seconds)
        {
            var timeSpan = TimeSpan.FromSeconds(seconds);
            return timeSpan.ToString(@"m\:ss");
        }
    }
}
