// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoLibrary.Models;

#nullable disable

namespace VideoLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250921161726_PostgresqlLegacyMode")]
    partial class PostgresqlLegacyMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VideoLibrary.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_last_updated");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_contents");

                    b.ToTable("contents", (string)null);
                });

            modelBuilder.Entity("VideoLibrary.Models.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_added");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("folder_path");

                    b.Property<int>("ImageCount")
                        .HasColumnType("integer")
                        .HasColumnName("image_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_path");

                    b.HasKey("Id")
                        .HasName("pk_galleries");

                    b.ToTable("galleries", (string)null);
                });

            modelBuilder.Entity("VideoLibrary.Models.GalleryTag", b =>
                {
                    b.Property<int>("GalleryId")
                        .HasColumnType("integer")
                        .HasColumnName("gallery_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("GalleryId", "TagId")
                        .HasName("pk_gallery_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_gallery_tags_tag_id");

                    b.ToTable("gallery_tags", (string)null);
                });

            modelBuilder.Entity("VideoLibrary.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LogLevel")
                        .HasColumnType("integer")
                        .HasColumnName("log_level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_log_entries");

                    b.ToTable("log_entries", (string)null);
                });

            modelBuilder.Entity("VideoLibrary.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateLastPlayed")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_last_played");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsShuffled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shuffled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer")
                        .HasColumnName("play_count");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_path");

                    b.Property<string>("VideoIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("video_ids");

                    b.HasKey("Id")
                        .HasName("pk_playlists");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("VideoLibrary.Models.PlaylistTag", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer")
                        .HasColumnName("playlist_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("PlaylistId", "TagId")
                        .HasName("pk_playlist_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_playlist_tags_tag_id");

                    b.ToTable("playlist_tags", (string)null);
                });

            modelBuilder.Entity("VideoLibrary.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_path");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("VideoLibrary.Models.Transcription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContentId")
                        .HasColumnType("integer")
                        .HasColumnName("content_id");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_completed");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_requested");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_transcriptions");

                    b.ToTable("transcriptions", (string)null);
                });

            modelBuilder.Entity("VideoLibrary.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioCodec")
                        .HasColumnType("text")
                        .HasColumnName("audio_codec");

                    b.Property<long?>("BitRate")
                        .HasColumnType("bigint")
                        .HasColumnName("bit_rate");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_added");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("text")
                        .HasColumnName("video_codec");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("VideoLibrary.Models.VideoTag", b =>
                {
                    b.Property<int>("VideoId")
                        .HasColumnType("integer")
                        .HasColumnName("video_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("VideoId", "TagId")
                        .HasName("pk_video_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_video_tags_tag_id");

                    b.ToTable("video_tags", (string)null);
                });

            modelBuilder.Entity("VideoLibrary.Models.GalleryTag", b =>
                {
                    b.HasOne("VideoLibrary.Models.Gallery", "Gallery")
                        .WithMany("GalleryTags")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gallery_tags_galleries_gallery_id");

                    b.HasOne("VideoLibrary.Models.Tag", "Tag")
                        .WithMany("GalleryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gallery_tags_tags_tag_id");

                    b.Navigation("Gallery");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VideoLibrary.Models.PlaylistTag", b =>
                {
                    b.HasOne("VideoLibrary.Models.Playlist", "Playlist")
                        .WithMany("PlaylistTags")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_tags_playlists_playlist_id");

                    b.HasOne("VideoLibrary.Models.Tag", "Tag")
                        .WithMany("PlaylistTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_tags_tags_tag_id");

                    b.Navigation("Playlist");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VideoLibrary.Models.VideoTag", b =>
                {
                    b.HasOne("VideoLibrary.Models.Tag", "Tag")
                        .WithMany("VideoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_tags_tags_tag_id");

                    b.HasOne("VideoLibrary.Models.Video", "Video")
                        .WithMany("VideoTags")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_tags_videos_video_id");

                    b.Navigation("Tag");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VideoLibrary.Models.Gallery", b =>
                {
                    b.Navigation("GalleryTags");
                });

            modelBuilder.Entity("VideoLibrary.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistTags");
                });

            modelBuilder.Entity("VideoLibrary.Models.Tag", b =>
                {
                    b.Navigation("GalleryTags");

                    b.Navigation("PlaylistTags");

                    b.Navigation("VideoTags");
                });

            modelBuilder.Entity("VideoLibrary.Models.Video", b =>
                {
                    b.Navigation("VideoTags");
                });
#pragma warning restore 612, 618
        }
    }
}
